/**
 * Writes skills/krea/references/operations.md from the operation catalog in
 * src/core/operation-dispatch.ts — the same source that validates requests —
 * so the skill can never document a parameter that doesn't exist.
 * Runs as part of `npm run build`.
 */
import fs from "node:fs";
import path from "node:path";
import { describeOperations } from "../src/core/operation-dispatch";

const OUT = path.resolve(import.meta.dirname, "..", "skills", "krea", "references", "operations.md");

const lines: string[] = [
  "# Edit operations",
  "",
  "<!-- Generated by scripts/gen-skill-reference.ts from src/core/operation-dispatch.ts. Do not edit by hand. -->",
  "",
  "Send them to `POST /api/agent/operations` as `{ \"projectPath\": \"…\", \"operations\": [ { \"op\": \"…\", … }, … ], \"dryRun\"?: true }`.",
  "They run in order; the batch is atomic (a malformed operation or an invalid result saves nothing).",
  "Each result is `{ index, op, applied, detail?, createdId?, createdIds? }` — `applied: false` means valid but nothing changed (see `detail`).",
  "Unknown parameters are rejected, so a typo is reported instead of silently ignored.",
  "2D-map operations work in grid cells; 3D-map operations in meters (x east, z south, y up). Using one kind on the other kind of map is rejected with a hint.",
  "",
];

/** Section headings, inserted before the first operation of each group. */
const SECTIONS: Record<string, string> = {
  placeObject: "2D maps (tile grid)",
  createLayer: "Layers (2D and 3D maps)",
  createMap: "Maps",
  addObjectDefinition: "Object catalog (shared by every map)",
  sculptTerrain: "3D maps: terrain",
  placeObject3D: "3D maps: objects",
};

for (const { op, description, params } of describeOperations()) {
  if (SECTIONS[op]) lines.push(`# ${SECTIONS[op]}`, "");
  lines.push(`## ${op}`, "", description, "");
  const entries = Object.entries(params);
  if (entries.length === 0) {
    lines.push("No parameters.", "");
    continue;
  }
  lines.push("| Parameter | Type | Required | Description |", "|---|---|---|---|");
  for (const [name, p] of entries) {
    lines.push(`| \`${name}\` | ${p.type} | ${p.required ? "yes" : "no"} | ${p.description.replace(/\|/g, "\\|")} |`);
  }
  lines.push("");
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${path.relative(process.cwd(), OUT)}`);
